### ISSUE TITLE
Loading the project, I get `not convertible to CLBeacon` error

### ISSUE THREAD

**Issue by eddiejaoude** [willdages/closest-beacon-demo#1]
![screenshot 2015-06-08 14 18 49](https://cloud.githubusercontent.com/assets/624760/8035552/671b4136-0de9-11e5-98f7-8a3f1658a8e1.png)

**Comment by willdages** [comment]
Thanks, it looks like this changed with Swift 1.2 in Xcode 6.3. It compiles for me if you accept the suggestion to use `as!`

I'll test more exhaustively this week to make sure everything works right, and then update the code, blog post, screencast, and eBook. Thanks for filing the issue!

**Comment by willdages** [comment]
Hey Eddie,

I updated the code last night to work with iOS9 and Xcode 7.1. This should be resolved now with the latest code, but please reopen if you are still experiencing a problem there. Thanks!
