### ISSUE TITLE
Can we detect beacon without knowing it's UUID ?

### ISSUE THREAD

**Issue by janeshsutharios** [willdages/closest-beacon-demo#3]
Can we detect nearby beacons without knowing it's UUID /Major/minor/identifier  ?

**Comment by willdages** [comment]
You need to know at least the UUID to start monitoring a region. The Major/Minor identifiers are optional.

[Source](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/LocationAwarenessPG/RegionMonitoring/RegionMonitoring.html#//apple_ref/doc/uid/TP40009497-CH9-SW8)

**Comment by janeshsutharios** [comment]
Will check! Thanks

**Comment by janeshsutharios** [comment]
@willdages Major/Minor are not optional
As per apple documentation -

> When detecting an iBeacon, you must specify the proximityUUID, major, and minor values that you programmed into the beacon hardware.
[https://developer.apple.com/documentation/corelocation/clbeaconregion](https://developer.apple.com/documentation/corelocation/clbeaconregion
)

**Comment by janeshsutharios** [comment]
Right 
https://developer.apple.com/documentation/corelocation/determining_the_proximity_to_an_ibeacon
